package sqar.db.model;

public class Coin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.dynasty
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String dynasty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.outline
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.width
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private Double width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.height
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.weight
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.material
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.nubmer
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String nubmer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.rate
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin.note
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.id
     *
     * @return the value of coin.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.id
     *
     * @param id the value for coin.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.dynasty
     *
     * @return the value of coin.dynasty
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.dynasty
     *
     * @param dynasty the value for coin.dynasty
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.outline
     *
     * @return the value of coin.outline
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.outline
     *
     * @param outline the value for coin.outline
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setOutline(String outline) {
        this.outline = outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.width
     *
     * @return the value of coin.width
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.width
     *
     * @param width the value for coin.width
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.height
     *
     * @return the value of coin.height
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.height
     *
     * @param height the value for coin.height
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.weight
     *
     * @return the value of coin.weight
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.weight
     *
     * @param weight the value for coin.weight
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.material
     *
     * @return the value of coin.material
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.material
     *
     * @param material the value for coin.material
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.nubmer
     *
     * @return the value of coin.nubmer
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getNubmer() {
        return nubmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.nubmer
     *
     * @param nubmer the value for coin.nubmer
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setNubmer(String nubmer) {
        this.nubmer = nubmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.rate
     *
     * @return the value of coin.rate
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.rate
     *
     * @param rate the value for coin.rate
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin.note
     *
     * @return the value of coin.note
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin.note
     *
     * @param note the value for coin.note
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }
}