package sqar.db.model;

public class CoinImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_img.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_img.coin_id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String coinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_img.pic_url
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_img.seq
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    private Integer seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_img.id
     *
     * @return the value of coin_img.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_img.id
     *
     * @param id the value for coin_img.id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_img.coin_id
     *
     * @return the value of coin_img.coin_id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_img.coin_id
     *
     * @param coinId the value for coin_img.coin_id
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setCoinId(String coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_img.pic_url
     *
     * @return the value of coin_img.pic_url
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_img.pic_url
     *
     * @param picUrl the value for coin_img.pic_url
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_img.seq
     *
     * @return the value of coin_img.seq
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_img.seq
     *
     * @param seq the value for coin_img.seq
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
}