package com.qpp.springmvc.dao.pojo;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.student_id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_category
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String projectCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.createtime
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.result
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.funds
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String funds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.team
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String team;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.introduction
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.research_contents
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String researchContents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.plan
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String plan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.student_id
     *
     * @return the value of project.student_id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.student_id
     *
     * @param studentId the value for project.student_id
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_category
     *
     * @return the value of project.project_category
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getProjectCategory() {
        return projectCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_category
     *
     * @param projectCategory the value for project.project_category
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setProjectCategory(String projectCategory) {
        this.projectCategory = projectCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.createtime
     *
     * @return the value of project.createtime
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.createtime
     *
     * @param createtime the value for project.createtime
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.result
     *
     * @return the value of project.result
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.result
     *
     * @param result the value for project.result
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.funds
     *
     * @return the value of project.funds
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getFunds() {
        return funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.funds
     *
     * @param funds the value for project.funds
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setFunds(String funds) {
        this.funds = funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.team
     *
     * @return the value of project.team
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.team
     *
     * @param team the value for project.team
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setTeam(String team) {
        this.team = team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.introduction
     *
     * @return the value of project.introduction
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.introduction
     *
     * @param introduction the value for project.introduction
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.research_contents
     *
     * @return the value of project.research_contents
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getResearchContents() {
        return researchContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.research_contents
     *
     * @param researchContents the value for project.research_contents
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setResearchContents(String researchContents) {
        this.researchContents = researchContents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.plan
     *
     * @return the value of project.plan
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getPlan() {
        return plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.plan
     *
     * @param plan the value for project.plan
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setPlan(String plan) {
        this.plan = plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbggenerated Mon Aug 28 10:47:06 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}