package sqar.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sqar.dao.model.Coin;
import sqar.dao.model.CoinExample;

public interface CoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int countByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int deleteByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int insert(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int insertSelective(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    List<Coin> selectByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    Coin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") Coin record, @Param("example") CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int updateByExample(@Param("record") Coin record, @Param("example") CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int updateByPrimaryKeySelective(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Sat Sep 30 10:14:34 CST 2017
     */
    int updateByPrimaryKey(Coin record);
}