package sqar.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sqar.db.model.CoinImg;
import sqar.db.model.CoinImgExample;

public interface CoinImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int countByExample(CoinImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int deleteByExample(CoinImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int insert(CoinImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int insertSelective(CoinImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    List<CoinImg> selectByExample(CoinImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    CoinImg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") CoinImg record, @Param("example") CoinImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByExample(@Param("record") CoinImg record, @Param("example") CoinImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByPrimaryKeySelective(CoinImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_img
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByPrimaryKey(CoinImg record);
}