package sqar.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import sqar.db.model.Coin;
import sqar.db.model.CoinExample;

public interface CoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int countByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int deleteByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int insert(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int insertSelective(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    List<Coin> selectByExample(CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    Coin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") Coin record, @Param("example") CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByExample(@Param("record") Coin record, @Param("example") CoinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByPrimaryKeySelective(Coin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin
     *
     * @mbggenerated Fri Sep 29 15:09:16 CST 2017
     */
    int updateByPrimaryKey(Coin record);
}